---
- hosts: web_nodes
  vars:
    os_packages:
      - python36
      - python36-pip
      - git
      - tree
      - mc
    bucket_name: "203494-bucket"
  tasks:
    - name: "Install os packages"
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ os_packages }}"
      become: yes
    - name: "sync my repo"
      git:
        repo: https://github.com/kbartosz12/aws_project.git
        dest: ~/ani-creator
    - name: "ensure env is configured"
      lineinfile:
        path: ~/.bashrc
        line: "export APP_BUCKET_NAME={{bucket_name}}"

    - raw: git config --global user.name "kbartosz"
    - raw: git config --global user.email "krzysztofbartosz12@gmail.com"


















    
     
  
